Default: &defaults
  user: root
  password: root
  host: localhost
  port: 5432
  database: haskellers
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: _haskellers_test
  <<: *defaults

Staging:
  database: haskellers_staging
  poolsize: 100
  <<: *defaults

Production:
  database: haskellers_production
  poolsize: 100
  <<: *defaults
